"""Jupyter HTML rendering of a TrustReport (all user-derived text is escaped).

Part of the TrustReport split (TL-18); behaviour is unchanged.
"""

from __future__ import annotations

import io
import logging
from typing import Any

from trustlens._palette import BRAND_COLORS
from trustlens._report.base import ReportBase
from trustlens._version import __version__

logger = logging.getLogger("trustlens.report")


class HtmlMixin(ReportBase):
    """Jupyter HTML rendering of a TrustReport (all user-derived text is escaped)."""

    def _repr_html_regression(self) -> str:
        """Simple text-based HTML for regression reports (no Phase-2 plots yet)."""
        import html as _html

        body = _html.escape(self._generate_regression_text())
        return (
            '<div style="font-family: monospace; max-width: 760px; padding: 18px; '
            'border: 1px solid #e0e0e0; border-radius: 12px; background:#fff;">'
            f'<pre style="white-space: pre-wrap; margin:0;">{body}</pre>'
            f'<div style="text-align:right; font-size:12px; color:#aaa; margin-top:10px;">'
            f"Generated by TrustLens v{__version__}</div></div>"
        )

    def _repr_html_(self) -> str:
        """Rich HTML representation for Jupyter notebooks.

        Every value derived from user data (feature names, model class,
        narrative text) is HTML-escaped (TL-08).
        """
        if self.task_type == "regression":
            return self._repr_html_regression()
        from html import escape

        def _esc(value: Any) -> str:
            return escape(str(value))

        import base64

        import matplotlib.pyplot as plt

        from trustlens.visualization.summary_plot import _color_for_grade

        # 1. Generate the summary plot into a buffer
        fig = self.summary_plot(show=False)
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
        plt.close(fig)
        data = base64.b64encode(buf.getbuffer()).decode("ascii")

        # 2. Build the HTML wrapper
        ts = self.trust_score
        gc = _color_for_grade(ts.grade)

        html = f"""
        <div style="font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                    max-width: 900px; padding: 25px; border-radius: 16px;
                    border: 1px solid #e0e0e0; background-color: #ffffff;
                    box-shadow: 0 8px 24px rgba(0,0,0,0.06); margin: 15px 0;">

            <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 25px;">
                <div>
                    <h2 style="margin: 0; color: {BRAND_COLORS["dark"]}; font-size: 24px; font-weight: 800;">TrustLens Analysis Report</h2>
                    <div style="font-size: 14px; color: {BRAND_COLORS["gray"]}; margin-top: 4px;">
                        {_esc(self.metadata["model_class"])} &bull; {self.metadata["n_samples"]:,} samples &bull; {self.metadata["timestamp"][:19].replace("T", " ")}
                    </div>
                </div>
                <div style="text-align: right;">
                    <div style="font-size: 42px; font-weight: 800; color: {gc}; line-height: 1;">{ts.score}<span style="font-size: 18px; color: {BRAND_COLORS["gray"]}; font-weight: 600;">/100</span></div>
                    <div style="font-size: 14px; font-weight: 700; color: {gc}; text-transform: uppercase;">Grade {_esc(ts.grade)}</div>
                </div>
            </div>

            <div style="background-color: #f8f9fa; border-radius: 12px; padding: 15px; margin-bottom: 25px; border-left: 5px solid {gc};">
                <div style="font-size: 15px; font-weight: 600; color: {BRAND_COLORS["dark"]}; margin-bottom: 5px;">Overall Assessment</div>
                <div style="font-size: 14px; color: #444;">{_esc(ts.verdict)}</div>
            </div>
        """

        exp = self.deployment_explanation
        fail_icon = "<span style='color: #d32f2f; font-weight: bold;'>✗</span>"
        pass_icon = "<span style='color: #2e7d32; font-weight: bold;'>✓</span>"

        reasons_html = "".join(
            [
                f'<li style="margin-bottom: 4px;">{fail_icon if r["status"] == "fail" else pass_icon} {_esc(r["message"])}</li>'
                for r in exp["reasons"]
            ]
        )
        pr_html = (
            f'<div style="font-size: 13px; font-weight: 700; color: {BRAND_COLORS["gray"]}; margin-top: 15px; margin-bottom: 4px; text-transform: uppercase;">Primary Risk</div><div style="font-size: 14px; color: #d32f2f; font-weight: 600;">{_esc(exp["primary_risk"]["metric"])}</div>'
            if exp["primary_risk"]
            else ""
        )
        recs_html = "".join(
            [f'<li style="margin-bottom: 4px;">{_esc(r)}</li>' for r in exp["recommendations"]]
        )

        html += f"""
            <div style="background-color: #ffffff; border: 1px solid #e0e0e0; border-radius: 12px; padding: 15px; margin-bottom: 25px;">
                <div style="font-size: 15px; font-weight: 600; color: {BRAND_COLORS["dark"]}; margin-bottom: 8px;">Deployment Verdict: <span style="font-weight: 700;">{_esc(exp["verdict"])}</span></div>
                {pr_html}
                <div style="display: flex; gap: 30px; margin-top: 15px; flex-wrap: wrap;">
                    <div style="flex: 1; min-width: 200px;">
                        <div style="font-size: 13px; font-weight: 700; color: {BRAND_COLORS["gray"]}; margin-bottom: 8px; text-transform: uppercase;">Reasons</div>
                        <ul style="margin: 0; padding-left: 0; list-style-type: none; font-size: 13.5px; color: #333; line-height: 1.5;">
                            {reasons_html}
                        </ul>
                    </div>
                    <div style="flex: 1; min-width: 250px;">
                        <div style="font-size: 13px; font-weight: 700; color: {BRAND_COLORS["gray"]}; margin-bottom: 8px; text-transform: uppercase;">Recommendations</div>
                        <ul style="margin: 0; padding-left: 20px; font-size: 13.5px; color: #333; line-height: 1.5;">
                            {recs_html}
                        </ul>
                    </div>
                </div>
            </div>

            <div style="margin-bottom: 20px;">
                <img src="data:image/png;base64,{data}" style="width: 100%; border-radius: 8px; border: 1px solid #f0f0f0;" />
            </div>

            <div style="display: flex; gap: 20px; flex-wrap: wrap;">
                <div style="flex: 1; min-width: 250px;">
                    <div style="font-size: 13px; font-weight: 700; color: {BRAND_COLORS["gray"]}; margin-bottom: 12px; text-transform: uppercase;">Key Observations</div>
                    <ul style="margin: 0; padding-left: 20px; font-size: 13.5px; color: #333; line-height: 1.6;">
        """

        insights = self._generate_insights()
        if not insights:
            html += "<li>No critical issues found.</li>"
        else:
            for insight in insights:
                html += f"<li>{_esc(insight)}</li>"

        html += f"""
                    </ul>
                </div>
            </div>

            <div style="margin-top: 25px; pt: 15px; border-top: 1px solid #f0f0f0; text-align: right;">
                <span style="font-size: 12px; color: #aaa;">Generated by TrustLens v{__version__}</span>
            </div>
        </div>
        """
        return html
