"""
trustlens.report.
=================
TrustReport — the central result container returned by ``analyze()``.

Responsibilities
----------------
* Store all computed metric results in a structured dictionary.
* Compute and expose the Trust Score (0–100).
* Provide human-readable console summaries via ``show()``.
* Render the summary dashboard via ``summary_plot()``.
* Surface critical failures via ``show_failures()``.
* Render per-module plots via ``plot()``.
* Persist the full report to disk via ``save()``.
* Support JSON serialization for downstream consumption.

Relationship to other components
--------------------------------
The `TrustReport` is constructed by the core pipeline (`trustlens.core.pipeline._run_analysis_pipeline`)
and acts as the final consumer of metric dictionaries generated by the analysis modules.
It relies on `trustlens.trust_score` to compute the composite Trust Score.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Optional

import numpy as np

from trustlens._report.base import _WEAK_EXPLAIN
from trustlens._report.bias_plots import BiasPlotMixin
from trustlens._report.html import HtmlMixin
from trustlens._report.io import PersistenceMixin
from trustlens._report.narrative import NarrativeMixin
from trustlens._report.plots import PlotMixin
from trustlens._report.text import TextReportMixin

logger = logging.getLogger(__name__)


class TrustReport(
    TextReportMixin, NarrativeMixin, PlotMixin, BiasPlotMixin, PersistenceMixin, HtmlMixin
):
    """
    Container for all TrustLens analysis results.

    The TrustReport orchestrates the display and serialization of analysis
    metrics computed during the `analyze()` workflow.

    Attributes
    ----------
    results : dict
      Nested dictionary keyed by module name containing the raw metrics.
    trust_score : TrustScoreResult
      Composite 0–100 trust score with sub-scores and grade.
    metadata : dict
      Run-level metadata (timestamp, library version, model class, etc.).
    model : Any
      Reference to the analyzed model (not serialized to JSON).
    X : np.ndarray
      Validation feature matrix.
    y_true : np.ndarray
      Ground-truth labels.
    y_pred : np.ndarray
      Predicted class labels.
    y_prob : np.ndarray, optional
      Predicted class probabilities.
    embeddings : np.ndarray, optional
      Latent representations used for representation analysis.
    framework : str, optional
      The framework string auto-detected or provided (e.g., 'sklearn').
    backend_metadata : dict
      Metadata regarding the backend resolution process.
    """

    def __init__(
        self,
        results: dict[str, Any],
        model: Any,
        X: np.ndarray,
        y_true: np.ndarray,
        y_pred: np.ndarray,
        y_prob: Optional[np.ndarray],
        embeddings: np.ndarray | None = None,
        framework: str | None = None,
        backend_metadata: dict[str, Any] | None = None,
        task_type: str = "classification",
        prediction_intervals: tuple[np.ndarray, np.ndarray] | None = None,
        predicted_variance: np.ndarray | None = None,
    ) -> None:
        self.results = results
        self.model = model
        self.X = X
        self.y_true = y_true
        self.y_pred = y_pred
        self.y_prob = y_prob
        self.embeddings = embeddings
        self.framework = framework
        self.backend_metadata = backend_metadata or {}
        self.task_type = task_type
        # Regression uncertainty inputs, retained so the regression visualizations
        # (e.g. the prediction-interval band in plot_residuals) are self-contained
        # from the report. Both are None for classification reports.
        self.prediction_intervals = prediction_intervals
        self.predicted_variance = predicted_variance
        self.metadata = self._build_metadata()

        self._patterns: list[str] = []
        if task_type == "regression":
            # Regression has its own scorer (RFC #145): the same TrustScoreResult
            # interface (0–100, A–D, verdicts, weight redistribution) over three
            # regression-native dimensions instead of the classification four.
            # The classification-only narrative (patterns, deployment_explanation,
            # summary_plot) stays guarded by _require_classification().
            from trustlens.trust_score import regression_trust_score

            self.trust_score = regression_trust_score(results, y_true)
        else:
            # Compute Trust Score immediately so it's always available
            from trustlens.trust_score import compute_trust_score

            self.trust_score = compute_trust_score(results)
            self._compute_patterns()

        self.metadata["score_version"] = self.trust_score.score_version
        self.metadata["partial"] = self.trust_score.is_partial
        if self.trust_score.missing_dimensions:
            self.metadata["missing_dimensions"] = list(self.trust_score.missing_dimensions)

    def _require_classification(self, feature: str) -> None:
        """Guard classification-only features against regression reports."""
        if self.task_type == "regression":
            raise NotImplementedError(
                f"{feature} is not available for regression reports. "
                "Use report.plot_residuals() / report.plot_error_distribution() for "
                "regression visualizations, or report.show() / report.to_dict() / "
                "report.trust_score for the regression reliability metrics and Trust Score."
            )

    def _require_regression(self, feature: str) -> None:
        """Guard regression-only features against classification reports."""
        if self.task_type != "regression":
            raise NotImplementedError(
                f"{feature} is only available for regression reports (this report is "
                f"'{self.task_type}'). Use report.plot() / report.summary_plot() for "
                "classification visualizations."
            )

    @property
    def patterns(self) -> list[str]:
        """Detected behavioral patterns (e.g. 'Confidently Wrong')."""
        return self._patterns

    def _compute_patterns(self) -> None:
        """Derive patterns directly from metrics."""
        failure_score = self.trust_score.sub_scores.get("failure", 100.0)
        ece = self.results.get("calibration", {}).get("ece", 0.0)
        conf_gap = self.results.get("failure", {}).get("confidence_gap", {}).get("gap", 0.0)

        # High-confidence errors mean avg confidence of mistakes is high
        avg_err_conf = (
            self.results.get("failure", {})
            .get("confidence_gap", {})
            .get("incorrect_confidence_mean", 0.0)
        )

        # Patterns only describe dimensions that were actually assessed; a
        # skipped module has no evidence and must not read as a perfect 0.0
        # (TL-17).
        has_failure = "failure" in self.trust_score.sub_scores
        has_calibration = "calibration" in self.trust_score.sub_scores

        # 1. Confidently Wrong
        if has_failure and (failure_score < 40 or avg_err_conf > 0.65) and conf_gap < 0.1:
            self._patterns.append("Confidently Wrong")

        # 2. Safe Failures
        if has_failure and failure_score < 60 and avg_err_conf < 0.5 and conf_gap > 0.15:
            self._patterns.append("Safe Failures")

        # 3. Calibration Drift
        if has_calibration and (ece > 0.1 or (failure_score > 70 and ece > 0.08)):
            self._patterns.append("Calibration Drift")

    @property
    def deployment_explanation(self) -> dict[str, Any]:
        """Provide a structured explanation for the deployment verdict."""
        self._require_classification("deployment_explanation")
        ts = self.trust_score
        grade_map = {
            "A": "PASS",
            "B": "CAUTION",
            "C": "CAUTION",
            "D": "BLOCK",
            "N/A": "INSUFFICIENT_EVIDENCE",
        }
        verdict = "BLOCK" if ts.is_blocked else grade_map.get(ts.grade, "CAUTION")

        reasons = []
        recommendations = []
        penalties = getattr(ts, "penalties_applied", {})

        # Recommendations mapping
        rec_map = {
            "calibration": "Consider probability calibration techniques such as temperature scaling or isotonic regression before deployment.",
            "fairness": "Investigate subgroup performance disparities and consider fairness constraints before deployment.",
            "failure": "Inspect high-confidence misclassifications and verify confidence-weighted error distributions.",
            "representation": "Review latent embedding quality; poor representation may indicate failure to capture fundamental class separation.",
        }

        # Map dimension to standard penalty name logic
        dim_to_penalty_key = {
            "calibration": "Calibration",
            "failure": "Failure",
            "bias": "Fairness",
            "representation": "Representation",
        }

        # Case-insensitive penalty key matching
        penalties_lower = {k.lower(): (k, v) for k, v in penalties.items()}

        for dim, dim_score in self.trust_score.sub_scores.items():
            expected_penalty_key = dim_to_penalty_key.get(dim, dim.title())

            if not penalties and dim_score < _WEAK_EXPLAIN:
                # Methodology 2.0: no penalties; a weak sub-score is the reason.
                reasons.append(
                    {
                        "status": "fail",
                        "message": f"{expected_penalty_key} below {_WEAK_EXPLAIN:.0f} "
                        f"({dim_score:.1f}/100)",
                    }
                )
                rec_key = "fairness" if dim == "bias" else dim
                if rec_key in rec_map:
                    recommendations.append(rec_map[rec_key])
            elif expected_penalty_key.lower() in penalties_lower:
                actual_key, _ = penalties_lower[expected_penalty_key.lower()]
                reasons.append({"status": "fail", "message": f"{actual_key} penalty applied"})
                # Map back to our recommendation keys
                rec_key = "fairness" if dim == "bias" else dim
                if rec_key in rec_map:
                    recommendations.append(rec_map[rec_key])
            else:
                reasons.append(
                    {"status": "pass", "message": f"{expected_penalty_key} assessment completed"}
                )

        if getattr(ts, "is_partial", False):
            recommendations.append(
                "Complete the assessment: supply predicted probabilities (y_prob) and run all "
                "core modules before relying on this verdict."
            )
        if not recommendations:
            recommendations.append("Model meets all trustworthiness criteria for deployment.")

        # Determine primary risk
        primary_risk = None
        if penalties:
            # Largest penalty
            matched_key = max(penalties.items(), key=lambda x: x[1])[0]
            primary_risk = {"metric": matched_key, "value": penalties[matched_key]}
        elif ts.sub_scores:
            # Lowest sub-score
            lowest_dim = min(ts.sub_scores.items(), key=lambda x: x[1])[0]
            primary_risk = {
                "metric": dim_to_penalty_key.get(lowest_dim, lowest_dim.title()),
                "value": ts.sub_scores[lowest_dim],
            }

        for blocker in getattr(ts, "blockers", []) or []:
            reasons.insert(0, {"status": "fail", "message": blocker})
        for cap in getattr(ts, "caps_applied", []) or []:
            if ts.grade == "N/A":
                cap = cap.replace(" (capped at grade C)", "")
            reasons.append({"status": "fail", "message": cap})

        return {
            "verdict": verdict,
            "reasons": reasons,
            "primary_risk": primary_risk,
            "recommendations": recommendations,
        }

    def _build_metadata(self) -> dict[str, Any]:
        """Collect run-level metadata."""
        from trustlens import __version__

        meta = {
            "trustlens_version": __version__,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "n_samples": int(len(self.y_true)),
            "model_class": type(self.model).__name__ if self.model is not None else "Manual",
            "modules_run": list(self.results.keys()),
            "task_type": self.task_type,
        }

        # n_classes is a classification concept; for regression report the
        # number of distinct target values instead.
        if self.task_type == "regression":
            meta["n_unique_targets"] = int(len(np.unique(self.y_true)))
        else:
            meta["n_classes"] = int(len(np.unique(self.y_true)))

        if self.framework:
            meta["framework"] = self.framework

        if self.backend_metadata:
            meta["backend"] = self.backend_metadata

        return meta

    def __repr__(self) -> str:
        modules_str = ", ".join(self.results.keys())
        if self.task_type == "regression":
            return (
                f"TrustReport(task='regression', "
                f"model={self.metadata['model_class']!r}, "
                f"samples={self.metadata['n_samples']}, "
                f"modules=[{modules_str}])"
            )
        return (
            f"TrustReport(model={self.metadata['model_class']!r}, "
            f"score={self.trust_score.score}/100 [{self.trust_score.grade}], "
            f"samples={self.metadata['n_samples']}, "
            f"modules=[{modules_str}])"
        )


# Backward-compatible names for helpers that moved with the TL-18 split.
from trustlens._report.plots import _danger_rating, _plot_failure_grid  # noqa: E402, F401
from trustlens._report.text import _methodology_lines, _score_summary_lines  # noqa: E402, F401
